version: 1.0.{build}
image: Visual Studio 2019
clone_depth: 1
init:
- ps: ''
environment:
  BOOST_ROOT: C:\Libraries\boost_1_71_0
  OPENSSL_ROOT_DIR: C:\OpenSSL-Win64
build_script:
- cmd: >-
    git remote add TrinityCoreCustomChanges https://github.com/TrinityCore/TrinityCoreCustomChanges.git
    
    git fetch TrinityCoreCustomChanges
    
    git checkout -b TrinityCoreCustomChanges/3.3.5-base_patch
        
    git checkout -b TrinityCoreCustomChanges/3.3.5-tele_npc_3
        
    git checkout -b TrinityCoreCustomChanges/3.3.5-lfgsolo
    
    git config user.email "appveyor@build.bot" && git config user.name "AppVeyor"

    git tag -a -m "AppVeyor build" init
    
    patch lfg-solo.patch
    
    patch Autobalance.patch
        
    patch -p1 < NPCBots.patch

    md build && cd build

    cmake -G"Visual Studio 16 2019" -A x64 -DSCRIPTS=dynamic -DTOOLS=True -DCMAKE_CXX_FLAGS=" /DWIN32 /D_WINDOWS /W3 /GR /EHsc /WX" -DCMAKE_C_FLAGS="/DWIN32 /D_WINDOWS /W3 /WX" ..

    "%programfiles(x86)%\Microsoft Visual Studio\2019\Community\MSBuild\Current\Bin\amd64\MsBuild.exe" /nologo /m:2 /p:Configuration=RelWithDebInfo /p:Platform="X64" /verbosity:minimal /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll" "TrinityCore.sln"

    cd bin\RelWithDebInfo\

    copy "C:\Program Files\MySQL\MySQL Server 5.7\lib\libmysql.dll" libmysql.dll

    copy "%OPENSSL_ROOT_DIR%\ssleay32.dll" ssleay32.dll

    copy "%OPENSSL_ROOT_DIR%\libeay32.dll" libeay32.dll

    cd ..

    7z a TrinityCoreWin64VS2019.zip .\RelWithDebInfo\*

    del /F /Q /S "RelWithDebInfo\*.pdb" > NUL

    7z a TrinityCoreWin64VS2019NoSymbols.zip .\RelWithDebInfo\*

test: off
artifacts:
- path: build\bin\TrinityCoreWin64VS2019.zip
  name: TrinityCoreWin64VS2019

- path: build\bin\TrinityCoreWin64VS2019NoSymbols.zip
  name: TrinityCoreWin64VS2019NoSymbols
